#!/bin/bash
let drp=( `ps aux | grep -i dropbear | awk '{print $2}' | grep -v root | wc -w`);
sh=( `ps aux | grep sshd | cut -d " " -f 1 | grep -v sshd | grep -v root | wc -w`);
todos=( `grep /home/ /etc/passwd | grep -v syslog | grep -v root | cut -d ":" -f1,5 | grep -v ntp | grep -v debian | wc -w`);
data=( `ps aux | grep -i dropbear | awk '{print $2}'`);

if [ $drp -le 2 ];
then
echo 'USUARIOS LOGUEADOS DROPBEAR   ' 0
else
echo 'USUARIOS LOGUEADOS DROPBEAR   ' $((drp -4))
fi
echo 'usuarios  -  conexiones'
for PID in "${data[@]}"
do
        NUM1=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | wc -l`;
        USER=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk '{print $10}'`;
        IP=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk '{print $12}'`;
        if [ $NUM1 -eq 1 ]; then
                echo $USER ':' $NUM1;
        fi
done
echo 'USUARIOS CONECTADOS EN SSH ' $((sh))
ps aux | grep sshd | cut -d " " -f 1 | grep -v sshd | grep -v root

echo 'USUARIOS DEL SISTEMA : ' $((todos))
grep /home/ /etc/passwd | grep -v syslog | grep -v root | cut -d ":" -f1,5 | grep -v ntp | grep -v debian

echo '========================================='
echo '>>>>>PANEL CODEERROR<<<<<'
echo '========================================='
