#!/bin/bash

totalc=( `ps aux | grep -i dropbear | awk '{print $2}' | wc -w | grep -v root`);
data=( `ps aux | grep -i dropbear | awk '{print $2}'`);

echo 'USUARIOS LOGUEADOS DROPBEAR   ' $((totalc -2))
echo 'usuarios  -  conexiones'
for PID in "${data[@]}"
do
        NUM1=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | wc -l`;
        USER=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk '{print $10}'`;
        IP=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk '{print $12}'`;
        if [ $NUM1 -eq 1 ]; then
                echo $USER ':' $NUM1;
        fi
done

data=( `ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'`);



echo "Usuarios [OpenSSH]";
echo "[x]";
TOTT=0
for PID in "${data[@]}"
do
        #echo "check $PID";
        NUM2=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | wc -l`;
        USER=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | awk '{print $9}'`;
        IP=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | awk '{print $11}'`;
        if [ $NUM2 -eq 1 ]; then
                echo "[PID] $PID - [Usuario]: $USER";
                echo "[TOTAL en OpenSSH]: $NUM2";
                TOTT=TOTT + 1;
        fi
        echo "$TOTT"
done
echo "=============================================="
echo "-------------CODEERROR-----------";
echo "=============================================="
